# Generated by Django 3.1.7 on 2021-02-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='type',
            field=models.CharField(choices=[('actual', 'actual'), ('forecast', 'forecast'), ('trend', 'trend')], default='actual', max_length=20),
            preserve_default=False,
        ),
    ]
